{
 "title": "MacOS CPU troubleshoot",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "AdhocFilters", "label": "Filters" },
   {
    "name": "process",
    "query": "label_values(cpu_usage, process)"
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 processes + PID",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "topk(10, cpu_usage)", "legendFormat": "{{process}} ({{pid}})" }
   ]
  },
  {
   "title": "i9-9980HK = 800% max",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(cpu_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "i9-9980HK = 800% max",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(cpu_usage)", "legendFormat": "Total CPU usage" }
   ]
  },
  {
   "title": "i9-9980HK = 19200 (base) or 40000 (turbo)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(cpu_usage)*2400/100", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "i9-9980HK = 19200 (base) or 40000 (turbo)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(cpu_usage)*2400/100", "legendFormat": "Total CPU usage in MHz" }
   ]
  },
  {
   "title": "Top 10 processes + PID",
   "type": "graph",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "topk(10, cpu_usage)", "legendFormat": "{{process}} ({{pid}})" }
   ]
  }
 ]
}