{
 "title": "MacOS processes",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "AdhocFilters", "label": "Filters" },
   {
    "name": "process",
    "query": "label_values(cpu_usage, process)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current CPU Usage (4 cores = 400%)",
   "type": "gauge",
   "description": "i7-7820HQ = 4*100=400%\ni7-7820HQ = 4*2900=11600MHz\n",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(cpu_usage)", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "Top 10 processes + PID",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 14, "x": 5, "y": 0 },
   "targets": [
    { "expr": "topk(10, cpu_usage)", "legendFormat": "{{process}} ({{pid}})" }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "description": "i7-7820HQ = 4*2900=11600MHz",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 0 },
   "targets": [
    { "expr": "sum(cpu_usage)*2900/100", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "Top 10 processes + PID",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "topk(10, cpu_usage)", "legendFormat": "{{process}} ({{pid}})" }
   ]
  }
 ]
}